name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - name: Build and push Docker image
      uses: docker/build-push-action@v3
      with:
        context: .
        file: .github/workflows/Dockerfile
        push: true
        tags: ${{ secrets.DOCKER_HUB_USERNAME }}/app:latest
