name: Docker Build and Test CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_HUB_USERNAME }}
        password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

    - name: Build Docker image
      uses: docker/build-push-action@v3
      with:
        context: .
        file: Dockerfile
        tags: ${{ secrets.DOCKER_HUB_USERNAME }}/app:latest

    - name: Run tests in Docker container
      run: |
        docker run --rm ${{ secrets.DOCKER_HUB_USERNAME }}/app:latest pytest

    - name: Push Docker image
      if: success()
      uses: docker/build-push-action@v3
      with:
        context: .
        file: Dockerfile
        push: true
        tags: ${{ secrets.DOCKER_HUB_USERNAME }}/app:latest

    - name: Trigger Render deploy
      if: success()
      env:
        RENDER_DEPLOY_HOOK: ${{ secrets.RENDER_DEPLOY_HOOK }}
      run: |
        curl -X POST $RENDER_DEPLOY_HOOK
