name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Build the Docker image
      run:  docker build -f .github/workflows/Dockerfile -t myapp .
    - name: Log in to Docker Hub
      run: echo "${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}" | docker login -u "${{ secrets.DOCKER_HUB_USERNAME }}" --password-stdin

    - name: Tag and Push Docker image
      run: |
          docker tag myapp ${{ secrets.DOCKER_HUB_USERNAME }}/myapp
          docker push ${{ secrets.DOCKER_HUB_USERNAME }}/myapp
