name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - name: Build Docker image
      run: docker build -t nadat/app_project7:tagname:latest
    - name: Push Docker image to DockerHub
      run: docker push nadat/app_project7:tagname:latest
